-- Create Admin User
-- Generated by Configuration Wizard

USE [FieldServiceDB];
GO

-- Check if admin user exists
IF NOT EXISTS (SELECT * FROM Users WHERE Username = 'admin')
BEGIN
    INSERT INTO Users (ID, Username, Email, FullName, Role, PasswordHash, IsActive, CreatedAt, CompanyCode)
    VALUES (
        'admin_001',
        'admin',
        'admin@dcpsp.com',
        'Joseph Ramon SR',
        'Admin',
        'YWJjMTIz',
        1,
        GETDATE(),
        'DCPSP'
    );
    PRINT 'Admin user created successfully';
END
ELSE
BEGIN
    -- Update existing admin user
    UPDATE Users
    SET Email = 'admin@dcpsp.com',
        FullName = 'Joseph Ramon SR',
        PasswordHash = 'YWJjMTIz',
        IsActive = 1,
        CompanyCode = 'DCPSP'
    WHERE Username = 'admin';
    PRINT 'Admin user updated successfully';
END
GO

-- Also create system user for automated tasks
IF NOT EXISTS (SELECT * FROM Users WHERE ID = 'system_001')
BEGIN
    INSERT INTO Users (ID, Username, Email, FullName, Role, PasswordHash, IsActive, CreatedAt, CompanyCode, Vendor)
    VALUES (
        'system_001',
        'system',
        'system@workzown.com',
        'System',
        'Admin',
        'bKE9UspwyIPg8LsQHkJaiehiTeUdstI5JZOvaoQRgJA=',
        1,
        GETDATE(),
        'DCPSP',
        'DCPSP'
    );
    PRINT 'System user created successfully';
END
GO
