-- Create Admin User
-- Generated by Configuration Wizard

USE [FieldServiceDB];
GO

-- Check if admin user exists
IF NOT EXISTS (SELECT * FROM Users WHERE Username = 'admin')
BEGIN
    INSERT INTO Users (ID, Username, Email, FullName, Role, PasswordHash, IsActive, CreatedAt)
    VALUES (
        'admin_001',
        'admin',
        'admin@dcpsp.com',
        'Joseph Ramon SR',
        'Admin',
        'YWJjMTIz',
        1,
        GETDATE()
    );
    PRINT 'Admin user created successfully';
END
ELSE
BEGIN
    -- Update existing admin user
    UPDATE Users
    SET Email = 'admin@dcpsp.com',
        FullName = 'Joseph Ramon SR',
        PasswordHash = 'YWJjMTIz',
        IsActive = 1
    WHERE Username = 'admin';
    PRINT 'Admin user updated successfully';
END
GO

-- Also create system user for automated tasks
IF NOT EXISTS (SELECT * FROM Users WHERE ID = 'system_001')
BEGIN
    INSERT INTO Users (ID, Username, Email, FullName, Role, PasswordHash, IsActive, CreatedAt)
    VALUES (
        'system_001',
        'system',
        'system@Knight Industries.com',
        'System',
        'Admin',
        'YWJjMTIz',
        1,
        GETDATE()
    );
    PRINT 'System user created successfully';
END
GO
