name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build frontend
        run: npm run build

      - name: Create release archive
        run: |
          zip -r field-service-plugins-${{ github.ref_name }}.zip . \
            -x "node_modules/*" \
            -x ".git/*" \
            -x "**/.DS_Store" \
            -x "**/*.log" \
            -x "**/dist/*.map"

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          artifacts: field-service-plugins-${{ github.ref_name }}.zip
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
